WITH steps_1_2 AS (
	SELECT
		-- Step 2 (create variables):
		v_BENE_ID,
		v_CLM_ID,
		v_LINE_NUM,
		v_CLM_THRU_DT,
		v_HCPCS_CD,
		v_LINE_NCH_PMT_AMT,
		v_LINE_ICD_DGNS_CD,
		EXTRACT(
			YEAR
			FROM
				v_CLM_THRU_DT
		) AS v_BENE_ENROLLMT_REF_YR
	FROM
		-- Step 1 (stack)
		(
			SELECT
				BENE_ID AS v_BENE_ID,
				CLM_ID AS v_CLM_ID,
				LINE_NUM AS v_LINE_NUM,
				CLM_THRU_DT AS v_CLM_THRU_DT,
				HCPCS_CD AS v_HCPCS_CD,
				LINE_NCH_PMT_AMT AS v_LINE_NCH_PMT_AMT,
				LINE_ICD_DGNS_CD AS v_LINE_ICD_DGNS_CD
			FROM
				_source_
			UNION ALL
			SELECT
				BENE_ID AS v_BENE_ID,
				CLM_ID AS v_CLM_ID,
				LINE_NUM AS v_LINE_NUM,
				CLM_THRU_DT AS v_CLM_THRU_DT,
				HCPCS_CD AS v_HCPCS_CD,
				LINE_NCH_PMT_AMT AS v_LINE_NCH_PMT_AMT,
				LINE_ICD_DGNS_CD AS v_LINE_ICD_DGNS_CD
			FROM
				`stanfordphs.medicare_20_2019_2020_carrier:0ynv:v1_0.carrier_line_file:p7va`
		)
) 
SELECT
	v_BENE_ID AS BENE_ID,
	v_CLM_ID AS CLM_ID,
	v_LINE_NUM AS LINE_NUM,
	v_CLM_THRU_DT AS CLM_THRU_DT,
	v_HCPCS_CD AS HCPCS_CD,
	v_LINE_ICD_DGNS_CD AS LINE_ICD_DGNS_CD,
	v_LINE_NCH_PMT_AMT AS LINE_NCH_PMT_AMT,
	v_BENE_ENROLLMT_REF_YR AS BENE_ENROLLMT_REF_YR
FROM
	`steps_1_2`