WITH step_1 AS (
	SELECT
		_source_.BENE_ID AS BENE_ID,
		_source_.CLM_ID AS CLM_ID,
		_source_.PRNCPAL_DGNS_CD AS PRNCPAL_DGNS_CD,
		_source_.ICD_DGNS_CD1 AS ICD_DGNS_CD1,
		_source_.ICD_DGNS_CD2 AS ICD_DGNS_CD2,
		_source_.ICD_DGNS_CD3 AS ICD_DGNS_CD3,
		_source_.ICD_DGNS_CD4 AS ICD_DGNS_CD4,
		_source_.ICD_DGNS_CD5 AS ICD_DGNS_CD5,
		_source_.ICD_DGNS_CD6 AS ICD_DGNS_CD6,
		_source_.ICD_DGNS_CD7 AS ICD_DGNS_CD7,
		_source_.ICD_DGNS_CD8 AS ICD_DGNS_CD8,
		_source_.ICD_DGNS_CD9 AS ICD_DGNS_CD9,
		_source_.ICD_DGNS_CD10 AS ICD_DGNS_CD10,
		_source_.ICD_DGNS_CD11 AS ICD_DGNS_CD11,
		_source_.ICD_DGNS_CD12 AS ICD_DGNS_CD12,
		_source_.ICD_DGNS_CD13 AS ICD_DGNS_CD13,
		_source_.ICD_DGNS_CD14 AS ICD_DGNS_CD14,
		_source_.ICD_DGNS_CD15 AS ICD_DGNS_CD15,
		_source_.ICD_DGNS_CD16 AS ICD_DGNS_CD16,
		_source_.ICD_DGNS_CD17 AS ICD_DGNS_CD17,
		_source_.ICD_DGNS_CD18 AS ICD_DGNS_CD18,
		_source_.ICD_DGNS_CD19 AS ICD_DGNS_CD19,
		_source_.ICD_DGNS_CD20 AS ICD_DGNS_CD20,
		_source_.ICD_DGNS_CD21 AS ICD_DGNS_CD21,
		_source_.ICD_DGNS_CD22 AS ICD_DGNS_CD22,
		_source_.ICD_DGNS_CD23 AS ICD_DGNS_CD23,
		_source_.ICD_DGNS_CD24 AS ICD_DGNS_CD24,
		_source_.ICD_DGNS_CD25 AS ICD_DGNS_CD25
	FROM
		_source_
		-- Step 1 (join):
		INNER JOIN `21_outpatient_rev_filter_eligible_hcpcs_output:7kaf` AS t1 ON _source_.BENE_ID = t1.BENE_ID
		AND _source_.CLM_ID = t1.CLM_ID
) 
SELECT
	BENE_ID,
	CLM_ID,
	PRNCPAL_DGNS_CD,
	ICD_DGNS_CD1,
	ICD_DGNS_CD2,
	ICD_DGNS_CD3,
	ICD_DGNS_CD4,
	ICD_DGNS_CD5,
	ICD_DGNS_CD6,
	ICD_DGNS_CD7,
	ICD_DGNS_CD8,
	ICD_DGNS_CD9,
	ICD_DGNS_CD10,
	ICD_DGNS_CD11,
	ICD_DGNS_CD12,
	ICD_DGNS_CD13,
	ICD_DGNS_CD14,
	ICD_DGNS_CD15,
	ICD_DGNS_CD16,
	ICD_DGNS_CD17,
	ICD_DGNS_CD18,
	ICD_DGNS_CD19,
	ICD_DGNS_CD20,
	ICD_DGNS_CD21,
	ICD_DGNS_CD22,
	ICD_DGNS_CD23,
	ICD_DGNS_CD24,
	ICD_DGNS_CD25
FROM
	`step_1`