WITH steps_1_3 AS (
	SELECT
		-- Step 2 (create variables):
		v_BENE_ID,
		v_NCH_CLM_TYPE_CD,
		v_SS_LS_SNF_IND_CD,
		v_DSCHRG_DT,
		v_PASS_THRU_AMT,
		v_MDCR_PMT_AMT,
		v_ADMTG_DGNS_CD,
		v_DGNS_1_CD,
		v_DGNS_2_CD,
		v_DGNS_3_CD,
		v_DGNS_4_CD,
		v_DGNS_5_CD,
		v_DGNS_6_CD,
		v_DGNS_7_CD,
		v_DGNS_8_CD,
		v_DGNS_9_CD,
		v_DGNS_10_CD,
		v_DGNS_11_CD,
		v_DGNS_12_CD,
		v_DGNS_13_CD,
		v_DGNS_14_CD,
		v_DGNS_15_CD,
		v_DGNS_16_CD,
		v_DGNS_17_CD,
		v_DGNS_18_CD,
		v_DGNS_19_CD,
		v_DGNS_20_CD,
		v_DGNS_21_CD,
		v_DGNS_22_CD,
		v_DGNS_23_CD,
		v_DGNS_24_CD,
		v_DGNS_25_CD,
		EXTRACT(
			YEAR
			FROM
				v_DSCHRG_DT
		) AS v_BENE_ENROLLMT_REF_YR
	FROM
		-- Step 1 (stack)
		(
			SELECT
				BENE_ID AS v_BENE_ID,
				NCH_CLM_TYPE_CD AS v_NCH_CLM_TYPE_CD,
				SS_LS_SNF_IND_CD AS v_SS_LS_SNF_IND_CD,
				DSCHRG_DT AS v_DSCHRG_DT,
				PASS_THRU_AMT AS v_PASS_THRU_AMT,
				MDCR_PMT_AMT AS v_MDCR_PMT_AMT,
				ADMTG_DGNS_CD AS v_ADMTG_DGNS_CD,
				DGNS_1_CD AS v_DGNS_1_CD,
				DGNS_2_CD AS v_DGNS_2_CD,
				DGNS_3_CD AS v_DGNS_3_CD,
				DGNS_4_CD AS v_DGNS_4_CD,
				DGNS_5_CD AS v_DGNS_5_CD,
				DGNS_6_CD AS v_DGNS_6_CD,
				DGNS_7_CD AS v_DGNS_7_CD,
				DGNS_8_CD AS v_DGNS_8_CD,
				DGNS_9_CD AS v_DGNS_9_CD,
				DGNS_10_CD AS v_DGNS_10_CD,
				DGNS_11_CD AS v_DGNS_11_CD,
				DGNS_12_CD AS v_DGNS_12_CD,
				DGNS_13_CD AS v_DGNS_13_CD,
				DGNS_14_CD AS v_DGNS_14_CD,
				DGNS_15_CD AS v_DGNS_15_CD,
				DGNS_16_CD AS v_DGNS_16_CD,
				DGNS_17_CD AS v_DGNS_17_CD,
				DGNS_18_CD AS v_DGNS_18_CD,
				DGNS_19_CD AS v_DGNS_19_CD,
				DGNS_20_CD AS v_DGNS_20_CD,
				DGNS_21_CD AS v_DGNS_21_CD,
				DGNS_22_CD AS v_DGNS_22_CD,
				DGNS_23_CD AS v_DGNS_23_CD,
				DGNS_24_CD AS v_DGNS_24_CD,
				DGNS_25_CD AS v_DGNS_25_CD
			FROM
				_source_
			UNION ALL
			SELECT
				BENE_ID AS v_BENE_ID,
				CAST(NCH_CLM_TYPE_CD AS STRING) AS v_NCH_CLM_TYPE_CD,
				SS_LS_SNF_IND_CD AS v_SS_LS_SNF_IND_CD,
				DSCHRG_DT AS v_DSCHRG_DT,
				PASS_THRU_AMT AS v_PASS_THRU_AMT,
				MDCR_PMT_AMT AS v_MDCR_PMT_AMT,
				ADMTG_DGNS_CD AS v_ADMTG_DGNS_CD,
				DGNS_1_CD AS v_DGNS_1_CD,
				DGNS_2_CD AS v_DGNS_2_CD,
				DGNS_3_CD AS v_DGNS_3_CD,
				DGNS_4_CD AS v_DGNS_4_CD,
				DGNS_5_CD AS v_DGNS_5_CD,
				DGNS_6_CD AS v_DGNS_6_CD,
				DGNS_7_CD AS v_DGNS_7_CD,
				DGNS_8_CD AS v_DGNS_8_CD,
				DGNS_9_CD AS v_DGNS_9_CD,
				DGNS_10_CD AS v_DGNS_10_CD,
				DGNS_11_CD AS v_DGNS_11_CD,
				DGNS_12_CD AS v_DGNS_12_CD,
				DGNS_13_CD AS v_DGNS_13_CD,
				DGNS_14_CD AS v_DGNS_14_CD,
				DGNS_15_CD AS v_DGNS_15_CD,
				DGNS_16_CD AS v_DGNS_16_CD,
				DGNS_17_CD AS v_DGNS_17_CD,
				DGNS_18_CD AS v_DGNS_18_CD,
				DGNS_19_CD AS v_DGNS_19_CD,
				DGNS_20_CD AS v_DGNS_20_CD,
				DGNS_21_CD AS v_DGNS_21_CD,
				DGNS_22_CD AS v_DGNS_22_CD,
				DGNS_23_CD AS v_DGNS_23_CD,
				DGNS_24_CD AS v_DGNS_24_CD,
				DGNS_25_CD AS v_DGNS_25_CD
			FROM
				`stanfordphs.medicare_20_2019_2020_medpar:0n7e:v1_0.medpar:pr0e`
		)
	WHERE
		-- Step 3 (rowFilter):
		(
			v_SS_LS_SNF_IND_CD = 'S'
			OR v_SS_LS_SNF_IND_CD = 'L'
		)
		AND (
			v_NCH_CLM_TYPE_CD = '60'
			OR v_NCH_CLM_TYPE_CD = '61'
		)
) 
SELECT
	v_BENE_ID AS BENE_ID,
	v_NCH_CLM_TYPE_CD AS NCH_CLM_TYPE_CD,
	v_SS_LS_SNF_IND_CD AS SS_LS_SNF_IND_CD,
	v_DSCHRG_DT AS DSCHRG_DT,
	v_ADMTG_DGNS_CD AS ADMTG_DGNS_CD,
	v_DGNS_1_CD AS DGNS_1_CD,
	v_DGNS_2_CD AS DGNS_2_CD,
	v_DGNS_3_CD AS DGNS_3_CD,
	v_DGNS_4_CD AS DGNS_4_CD,
	v_DGNS_5_CD AS DGNS_5_CD,
	v_DGNS_6_CD AS DGNS_6_CD,
	v_DGNS_7_CD AS DGNS_7_CD,
	v_DGNS_8_CD AS DGNS_8_CD,
	v_DGNS_9_CD AS DGNS_9_CD,
	v_DGNS_10_CD AS DGNS_10_CD,
	v_DGNS_11_CD AS DGNS_11_CD,
	v_DGNS_12_CD AS DGNS_12_CD,
	v_DGNS_13_CD AS DGNS_13_CD,
	v_DGNS_14_CD AS DGNS_14_CD,
	v_DGNS_15_CD AS DGNS_15_CD,
	v_DGNS_16_CD AS DGNS_16_CD,
	v_DGNS_17_CD AS DGNS_17_CD,
	v_DGNS_18_CD AS DGNS_18_CD,
	v_DGNS_19_CD AS DGNS_19_CD,
	v_DGNS_20_CD AS DGNS_20_CD,
	v_DGNS_21_CD AS DGNS_21_CD,
	v_DGNS_22_CD AS DGNS_22_CD,
	v_DGNS_23_CD AS DGNS_23_CD,
	v_DGNS_24_CD AS DGNS_24_CD,
	v_DGNS_25_CD AS DGNS_25_CD,
	v_PASS_THRU_AMT AS PASS_THRU_AMT,
	v_MDCR_PMT_AMT AS MDCR_PMT_AMT,
	v_BENE_ENROLLMT_REF_YR AS BENE_ENROLLMT_REF_YR
FROM
	`steps_1_3`