WITH step_1 AS (
	SELECT
		v_BENE_ID,
		v_BENE_ENROLLMT_REF_YR,
		v_HOP_MDCR_PMT,
		v_ACUTE_MDCR_PMT,
		v_ACUTE_PERDIEM_PMT,
		v_OIP_MDCR_PMT,
		v_OIP_PERDIEM_PMT,
		v_SNF_MDCR_PMT,
		v_HOS_MDCR_PMT,
		v_HH_MDCR_PMT,
		v_ASC_MDCR_PMT,
		v_PTB_DRUG_MDCR_PMT,
		v_EM_MDCR_PMT,
		v_ANES_MDCR_PMT,
		v_DIALYS_MDCR_PMT,
		v_OPROC_MDCR_PMT,
		v_IMG_MDCR_PMT,
		v_TEST_MDCR_PMT,
		v_DME_MDCR_PMT,
		v_OTHC_MDCR_PMT,
		v_PHYS_MDCR_PMT,
		v_PTD_MDCR_PMT
	FROM
		-- Step 1 (stack)
		(
			SELECT
				BENE_ID AS v_BENE_ID,
				BENE_ENROLLMT_REF_YR AS v_BENE_ENROLLMT_REF_YR,
				HOP_MDCR_PMT AS v_HOP_MDCR_PMT,
				ACUTE_MDCR_PMT AS v_ACUTE_MDCR_PMT,
				ACUTE_PERDIEM_PMT AS v_ACUTE_PERDIEM_PMT,
				OIP_MDCR_PMT AS v_OIP_MDCR_PMT,
				OIP_PERDIEM_PMT AS v_OIP_PERDIEM_PMT,
				SNF_MDCR_PMT AS v_SNF_MDCR_PMT,
				HOS_MDCR_PMT AS v_HOS_MDCR_PMT,
				HH_MDCR_PMT AS v_HH_MDCR_PMT,
				ASC_MDCR_PMT AS v_ASC_MDCR_PMT,
				PTB_DRUG_MDCR_PMT AS v_PTB_DRUG_MDCR_PMT,
				EM_MDCR_PMT AS v_EM_MDCR_PMT,
				ANES_MDCR_PMT AS v_ANES_MDCR_PMT,
				DIALYS_MDCR_PMT AS v_DIALYS_MDCR_PMT,
				OPROC_MDCR_PMT AS v_OPROC_MDCR_PMT,
				IMG_MDCR_PMT AS v_IMG_MDCR_PMT,
				TEST_MDCR_PMT AS v_TEST_MDCR_PMT,
				DME_MDCR_PMT AS v_DME_MDCR_PMT,
				OTHC_MDCR_PMT AS v_OTHC_MDCR_PMT,
				PHYS_MDCR_PMT AS v_PHYS_MDCR_PMT,
				PTD_MDCR_PMT AS v_PTD_MDCR_PMT
			FROM
				_source_
			UNION ALL
			SELECT
				BENE_ID AS v_BENE_ID,
				BENE_ENROLLMT_REF_YR AS v_BENE_ENROLLMT_REF_YR,
				HOP_MDCR_PMT AS v_HOP_MDCR_PMT,
				ACUTE_MDCR_PMT AS v_ACUTE_MDCR_PMT,
				CAST(ACUTE_PERDIEM_PMT AS STRING) AS v_ACUTE_PERDIEM_PMT,
				OIP_MDCR_PMT AS v_OIP_MDCR_PMT,
				CAST(OIP_PERDIEM_PMT AS STRING) AS v_OIP_PERDIEM_PMT,
				SNF_MDCR_PMT AS v_SNF_MDCR_PMT,
				HOS_MDCR_PMT AS v_HOS_MDCR_PMT,
				HH_MDCR_PMT AS v_HH_MDCR_PMT,
				ASC_MDCR_PMT AS v_ASC_MDCR_PMT,
				PTB_DRUG_MDCR_PMT AS v_PTB_DRUG_MDCR_PMT,
				EM_MDCR_PMT AS v_EM_MDCR_PMT,
				ANES_MDCR_PMT AS v_ANES_MDCR_PMT,
				DIALYS_MDCR_PMT AS v_DIALYS_MDCR_PMT,
				OPROC_MDCR_PMT AS v_OPROC_MDCR_PMT,
				IMG_MDCR_PMT AS v_IMG_MDCR_PMT,
				TEST_MDCR_PMT AS v_TEST_MDCR_PMT,
				DME_MDCR_PMT AS v_DME_MDCR_PMT,
				OTHC_MDCR_PMT AS v_OTHC_MDCR_PMT,
				PHYS_MDCR_PMT AS v_PHYS_MDCR_PMT,
				PTD_MDCR_PMT AS v_PTD_MDCR_PMT
			FROM
				`stanfordphs.medicare_20_2019_2020_enrollment_summary:2ewt:v1_0.master_beneficiary_summary_file_mbsf_cost_and_utilization:h0vk`
		)
) 
SELECT
	v_BENE_ID AS BENE_ID,
	v_BENE_ENROLLMT_REF_YR AS BENE_ENROLLMT_REF_YR,
	v_HOP_MDCR_PMT AS HOP_MDCR_PMT,
	v_ACUTE_MDCR_PMT AS ACUTE_MDCR_PMT,
	v_OIP_MDCR_PMT AS OIP_MDCR_PMT,
	v_SNF_MDCR_PMT AS SNF_MDCR_PMT,
	v_HOS_MDCR_PMT AS HOS_MDCR_PMT,
	v_HH_MDCR_PMT AS HH_MDCR_PMT,
	v_ASC_MDCR_PMT AS ASC_MDCR_PMT,
	v_PTB_DRUG_MDCR_PMT AS PTB_DRUG_MDCR_PMT,
	v_EM_MDCR_PMT AS EM_MDCR_PMT,
	v_ANES_MDCR_PMT AS ANES_MDCR_PMT,
	v_DIALYS_MDCR_PMT AS DIALYS_MDCR_PMT,
	v_OPROC_MDCR_PMT AS OPROC_MDCR_PMT,
	v_IMG_MDCR_PMT AS IMG_MDCR_PMT,
	v_TEST_MDCR_PMT AS TEST_MDCR_PMT,
	v_DME_MDCR_PMT AS DME_MDCR_PMT,
	v_OTHC_MDCR_PMT AS OTHC_MDCR_PMT,
	v_PHYS_MDCR_PMT AS PHYS_MDCR_PMT,
	v_PTD_MDCR_PMT AS PTD_MDCR_PMT,
	v_ACUTE_PERDIEM_PMT AS ACUTE_PERDIEM_PMT,
	v_OIP_PERDIEM_PMT AS OIP_PERDIEM_PMT
FROM
	`step_1`