WITH step_1 AS (
	SELECT
		_source_.BENE_ID AS BENE_ID,
		_source_.BENE_ENROLLMT_REF_YR AS BENE_ENROLLMT_REF_YR,
		_source_.HOP_MDCR_PMT AS HOP_MDCR_PMT,
		_source_.ACUTE_MDCR_PMT AS ACUTE_MDCR_PMT,
		_source_.OIP_MDCR_PMT AS OIP_MDCR_PMT,
		_source_.SNF_MDCR_PMT AS SNF_MDCR_PMT,
		_source_.HOS_MDCR_PMT AS HOS_MDCR_PMT,
		_source_.HH_MDCR_PMT AS HH_MDCR_PMT,
		_source_.ASC_MDCR_PMT AS ASC_MDCR_PMT,
		_source_.PTB_DRUG_MDCR_PMT AS PTB_DRUG_MDCR_PMT,
		_source_.EM_MDCR_PMT AS EM_MDCR_PMT,
		_source_.ANES_MDCR_PMT AS ANES_MDCR_PMT,
		_source_.DIALYS_MDCR_PMT AS DIALYS_MDCR_PMT,
		_source_.OPROC_MDCR_PMT AS OPROC_MDCR_PMT,
		_source_.IMG_MDCR_PMT AS IMG_MDCR_PMT,
		_source_.TEST_MDCR_PMT AS TEST_MDCR_PMT,
		_source_.DME_MDCR_PMT AS DME_MDCR_PMT,
		_source_.OTHC_MDCR_PMT AS OTHC_MDCR_PMT,
		_source_.PHYS_MDCR_PMT AS PHYS_MDCR_PMT,
		_source_.PTD_MDCR_PMT AS PTD_MDCR_PMT,
		_source_.ACUTE_PERDIEM_PMT AS ACUTE_PERDIEM_PMT,
		_source_.OIP_PERDIEM_PMT AS OIP_PERDIEM_PMT
	FROM
		_source_
		-- Step 1 (join):
		INNER JOIN `demo:1mds` AS t1 ON _source_.BENE_ID = t1.BENE_ID
		AND _source_.BENE_ENROLLMT_REF_YR = t1.BENE_ENROLLMT_REF_YR
) 
SELECT
	BENE_ID,
	BENE_ENROLLMT_REF_YR,
	HOP_MDCR_PMT,
	ACUTE_MDCR_PMT,
	OIP_MDCR_PMT,
	SNF_MDCR_PMT,
	HOS_MDCR_PMT,
	HH_MDCR_PMT,
	ASC_MDCR_PMT,
	PTB_DRUG_MDCR_PMT,
	EM_MDCR_PMT,
	ANES_MDCR_PMT,
	DIALYS_MDCR_PMT,
	OPROC_MDCR_PMT,
	IMG_MDCR_PMT,
	TEST_MDCR_PMT,
	DME_MDCR_PMT,
	OTHC_MDCR_PMT,
	PHYS_MDCR_PMT,
	PTD_MDCR_PMT,
	ACUTE_PERDIEM_PMT,
	OIP_PERDIEM_PMT
FROM
	`step_1`